from dash import dcc, html

layout = html.Div([
    html.H1('Sansty Dash', className='w3-center'),
    html.Article([
        html.Header(html.H2('Dash 示例', className='w3-center'),),
        dcc.Link('一个简单的例子', href='/examples/intro',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('回调更新文本输入', href='/examples/callback',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('回调更新图表', href='/examples/figure-n-slider',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('多输入回调', href='/examples/multiple-inputs',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('多输出回调', href='/examples/multiple-outputs',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('链式回调', href='/examples/chained-callback',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('表单回调', href='/examples/table-callback',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('状态回调', href='/examples/state-callback',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('打印图的属性', href='/examples/print-graph',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('悬停更新图', href='/examples/hover-update-graph',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('图的交叉过滤', href='/examples/cross-filter',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('阻止更新', href='/examples/prevent-update',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('部分更新', href='/examples/no-update',
                 className='w3-padding'),
        html.Br(),
        dcc.Link('callback context', href='/examples/callback-context',
                 className='w3-padding'),
    ], className='w3-pale-blue w3-padding')
])
